version: '3'
services:
  frontend:
    build: .
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定します。
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd frontend && yarn start'
    ports:
      - 8000:3000
    tty: true
  flask:
    build: ./flask
    volumes:
      - ./flask:/root/
    ports:
      - 5000:5000
